<?php

/**
 * Implements hook_page_attachments().
 * Makes sure libraries are attached on page render.
 */
function carei_resources_page_attachments(array &$attachments) {
  if (floatval(\Drupal::VERSION) >= 9.0) {
    $attachments['#attached']['library'][] = 'carei_resources/carei_folwell_accordion_d9';
  } else {
    $attachments['#attached']['library'][] = 'carei_resources/carei_folwell_accordion';
  }
}

/**
 * Implements hook_theme().
 * Defines templates used by this module.
 */
function carei_resources_theme($existing, $type, $theme, $path) {

  return [
    'group_accordion_view' => [
     'variables' => [
       'menu' => null,
       'before' => null,
       'group' => null,
       'after' => null
     ],
    ]
  ];
}
